---
title: "EDA-Project Text Mining"
author: "Eugénie Mathieu"
date: "27 11 2020"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
```

```{r load myData, include=FALSE}
load("data.RData")
```

```{r libraries,  echo = FALSE}
library(tidyverse)
library(tidytext)
library(bookdown)
library(tokenizers)
library(wordcloud2)
library(tibble)
library(knitr)
library(gghighlight)
library(quanteda)
library(devtools)
library(kableExtra)
library(tm)
devtools::install_github("dgrtwo/drlib")
force = TRUE

```
 ## Test avec le whole set de Boris
```{r fig= "15 most common words in Boris Johnson's speech on March 16th", echo = FALSE}
boris16mars_dtm <- VectorSource(boris16mars) %>% VCorpus() %>%  DocumentTermMatrix(control=list(removePunctuation=TRUE, removeNumbers=TRUE, stopwords=TRUE))
boris16mars_tidy <- tidy(boris16mars_dtm)
boris16mars_tidy %>%
  group_by(document) %>%
  top_n(15) %>%
  ungroup() %>%
  mutate(document = factor(as.numeric(document), levels = 1:17)) %>%
  ggplot(aes(drlib::reorder_within(term, count, document), count, fill =term)) +
  theme(legend.position = "none") +
  ggtitle("15 most common words in Boris Johnson's speech on March 16th") +
  xlab("Word") + ylab("Frequency") +
  geom_bar(stat = "identity") +
  drlib::scale_x_reordered() +
  coord_flip() +
  facet_wrap(~ document, scales = "free")
```



## tokenization of the speech of Boris Johnson
```{r Boris tokenization and frequency, echo = FALSE}
boris <- tibble(txt = boris16mars)

boris16mars.fr<- boris %>% unnest_tokens(word, txt) %>%
  anti_join(stop_words, by = "word") %>%group_by(word) %>% summarize(Count =n()) %>% 
  arrange(desc(Count)) 
boris %>%
  unnest_tokens(word, txt) %>%
  anti_join(stop_words, by = "word") %>%group_by(word) %>% summarize(Count =n()) %>% 
  arrange(desc(Count)) %>%
  kable() %>% kable_styling()

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


```{r Full spring speech Boris Cleaning and DTM, echo=FALSE}
BORIS.cp <- VCorpus(VectorSource(BORIS))

BORIS.cp <- tm_map(BORIS.cp, removePunctuation) 
BORIS.cp <- tm_map(BORIS.cp, removeNumbers)
BORIS.cp <- tm_map(BORIS.cp, removeWords, stopwords("english"))
BORIS.cp <- tm_map(BORIS.cp, content_transformer(tolower))
BORIS.cp <- tm_map(BORIS.cp, stripWhitespace)
BORIS.dtm <- DocumentTermMatrix(BORIS.cp) %>% tidy()
BORIS.tfidf <- DocumentTermMatrix(BORIS.cp, control = list(weighting = weightTfIdf))
inspect(BORIS.tfidf)
```

```{r Full spring speech Boris Cloud, echo=FALSE}
BORISquanteda.cp <- corpus(BORIS)
BORISquanteda.tk <- tokens(BORISquanteda.cp, remove_numbers=TRUE, remove_punct=TRUE, remove_symbols=TRUE, remove_separators=TRUE) %>% tokens_tolower() %>% tokens_remove(stopwords("english"))
BORISquanteda.dfm <- dfm(BORISquanteda.tk)
BORISquanteda.tfidf <- dfm_tfidf(BORISquanteda.dfm)
textplot_wordcloud(BORISquanteda.tfidf)

```


```{r Full spring speech Boris Zipfs Law, echo=FALSE}
BORIS.freq <- textstat_frequency(BORISquanteda.dfm)

BORIS.freq %>% ggplot(aes(x= rank , y= frequency))+
  geom_point() +
  geom_text(aes(label=ifelse(frequency>24,as.character(feature),'')),hjust=-1,vjust=0) +
  ggtitle("Zipf's law applied on speeches of Boris Johnson related to \ncovid-19 in between March 9th and 22nd") +
  xlab("Rank of words among documents") + 
    ylab("Frequency of the terms")


```
```{r BORIS All speeches Sentiment plot, echo=FALSE}
summary(BORISquanteda.cp)
library(lexicon) 
BORISquanteda.dfm
BORISquanteda.tk %>% tokens_lookup(dictionary = data_dictionary_LSD2015) %>% 
  dfm() %>% 
  tidy() %>% 
  ggplot(aes(x=document, y=count, fill=term)) + 
  geom_bar(stat="identity") + 
  coord_flip() +
  geom_text(aes(label = count), size = 3, hjust = 5, vjust = 0, position =     "stack")
```




