# Word Embedding

## Boris Johnson

## Word embedding

Here, we compute the co-occurence matrix. We use the fcm function from quanteda. We use a window lenght 5. 


```{r,warning=FALSE}
speech.coo.boris<-fcm(corpus_boris,context="window",window=5, tri=FALSE)
```

```{r,warning=FALSE}
p<-2 #word embedding dimension
speech.glove.boris<-GlobalVectors$new(rank = p,x_max = 10) #xmas is a neede technical option
speech.weC.boris<-speech.glove.boris$fit_transform(speech.coo.boris)
```
For illustration purpose, we now plot the 50 most used terms

```{r,warning=FALSE}
n.w.boris<-apply(corpus_boris.dfm,2,sum) #compute the number of times each term is used
index<-order(n.w.boris,decreasing = TRUE)[1:50]
plot(speech.weC.boris[index,],type = "n",xlab = "Dimension 1", ylab = "Dimendion 2")
text(x=speech.weC.boris[index,],labels = rownames(speech.weC.boris[index,]))
```

```{r,warning=FALSE}
speech.dtm <- corpus_boris.dfm
speech.rwmd.model.boris<-RelaxedWordMoversDistance$new(corpus_boris.dfm,speech.weC.boris)
speech.rwms.boris<-speech.rwmd.model.boris$sim2(corpus_boris.dfm)
speech.rwmd.boris<-speech.rwmd.model.boris$dist2(corpus_boris.dfm)

speech.hc.boris<-hclust(as.dist(speech.rwmd.boris))
plot(speech.hc.boris,cex=0.8)

```

We can observe that there is some coherence within the groups in terms the date of the speech. 

```{r,warning=FALSE}
speech.cl.boris<- cutree(speech.hc.boris,k=4)
corpus_boris.dfm[speech.cl.boris==1,]
```



## Macron

## Comparison